### PR TITLE
Better logging

### PR DESCRIPTION
**Pull request by Threated**
This now fully utilizes tracing for recording log messages.
The one downside this has is that we aren't able to show the IP Address as a fallback if the request does not get authenticated.
The upside is that all other log messages within this `Span` now automatically show the spans recorded context which in this case is which app issued the request.

I am also considering adding `url` and `method` to the spans context as that might be useful for debugging but I didn't like the way the spans fields were formatted for the common request logging case.

### CODE REVIEW

**Comment by TKussel** [comment]
Thanks for tackling the logging, I will look into this PR later. However, I think falling back to IP addresses is quite important to diagnose misbehaving clients. Many of the issues we observe include invalid authentication credentials (e.g. expired certificates), so we would not be easily able to identify those clients in the logs, right?

**Comment by Threated** [comment]
That's true maybe we should add this kind of IP logging for the Span of the authentication code so we can log it if we need it.

**Comment by TKussel** [comment]
Can you give me a quick update on this PR? If I see correctly, you added IP logging during authentication?

**Comment by Threated** [comment]
Should be ready to review again @TKussel

**Review by lablans — APPROVED** [review]

**Pull request merged**
