### PR TITLE
Expire tasks

### PR DESCRIPTION
**Pull request by lablans**
- [x] Update API docs
- [x] Update tests
- [x] Bump version to 0.3 to reflect non downwards-compatible API change
- [x] @TKussel , please re-run examples from Getting Started guide and adapt as necessary

### CODE REVIEW

**Review by TKussel — CHANGES_REQUESTED** [review]

**Comment by lablans** [comment]
> * Expunging tasks does not trigger the long polling of the task-creating party. I think they should be informed that the task expired.

Good point -- fixed in f71884e

> * Tasks with associated results are not deleted. The results are retrievable, as well as the tasks, even after `ttl` reaches `0`.

Are you sure? I wrote a specific test for that case which works fine: https://github.com/samply/beam/blob/41827fc46e73a24b227a66c2309966d26af8c8f3/dev/test_3_retrieve_via_todo.sh#L37-L51

Could you please re-check (both issues) and write reproducible tests?

**Comment by TKussel** [comment]
I rebased the branch fully to include all API changes. The automated test cases still fail, as some tasks are not correctly removed.

**Comment by TKussel** [comment]
@lablans Any update on this?

**Comment by lablans** [comment]
This regression was caused by https://github.com/samply/beam/commit/a64b3e5f64397b576adc5d116de4506bd5f12e56#r81433982 and has now been fixed.

**Comment by lablans** [comment]
> I rebased the branch fully to include all API changes. The automated test cases still fail, as some tasks are not correctly removed.

This regression was caused by https://github.com/samply/beam/commit/a64b3e5f64397b576adc5d116de4506bd5f12e56#r81433982 and has now been fixed.

**Comment by TKussel** [comment]
Again, I can retrieve expired (and claimed) tasks by using the `v1/tasks?to=<appid>` filter. I will write an automated test for this.

**Comment by lablans** [comment]
> Again, I can retrieve expired (and claimed) tasks by using the `v1/tasks?to=<appid>` filter. I will write an automated test for this.

Thank you, fixed in [#21281f9](https://github.com/samply/beam/pull/46/commits/21281f943799ae1a00e193b4c9f0ff6c71342212)

**Pull request merged**
