### PR TITLE
Fix connection timeout check to broker

### PR DESCRIPTION
**Pull request by Threated**
I spend around 15min trying to find a better solution to fix this and failed.

### CODE REVIEW

**Comment by lablans** [comment]
Strange. The original implementation looked nice, this feels like a downgrade. Do you consider this an upstream bug in hyper? Would you consider opening an issue there?

**Comment by Threated** [comment]
I imagine it has to do with all the different connectors we are using and one of them does not tell hyper that it is infact a timeout.

**Comment by Threated** [comment]
It also really does not help that this error type from hyper is not really public. So it is difficult to match on it.

**Comment by TKussel** [comment]
While cursed, this solution nicely encapsulates the cursed parts and gives sufficient context on why this code exists.

**Pull request merged**
